casters = {
    ## Cygnar
    'nemo3': 'Artificer General Nemo',
    'finch1': 'Storm Chaser Finch',
    'caine3': 'Caine\'s Hellslingers',
    'jakes2': 'Captain Allison Jakes',
    'caine2': 'Captain Allistar Caine',
    'darius1': 'Captain E. Dominic Darius',
    'kraye1': 'Captain Jeremiah Kraye',
    'sloan1': 'Captain Kara Sloan',
    'haley1': 'Captain Victoria Haley',
    'brisbane2': 'Colonel Markus \'Siege\' Brisbane',
    'nemo1': 'Commander Adept Nemo',
    'stryker1': 'Commander Coleman Stryker',
    'sturgis1': 'Commander Dalin Sturgis',
    'blaize1': 'Constance Blaize, Knight of the Prophet',
    'nemo2': 'General Adept Nemo',
    'caine1': 'Lieutenant Allister Caine',
    'stryker2': 'Lord Commander Stryker',
    'stryker3': 'Lord General Coleman Stryker',
    'maddox1': 'Major Beth Maddox',
    'brisbane1': 'Major Markus \'Siege\' Brisbane',
    'haley3': 'Major Prime Victoria Haley',
    'haley2': 'Major Victoria Haley',
    ## Khador
    'strakhov2': 'Assault Kommander Strakhov & Kommandos',
    'sorscha2': 'Forward Kommander Sorscha',
    'karchev1': 'Karchev the Terrible',
    'zerkova1': 'Koldun Kommander Aleksandra Zerkova',
    'irusk1': 'Kommandant Irusk',
    'sorscha3': 'Kommandant Sorscha Kratikoff',
    'malakov2': 'Kommander Andrei Malakov',
    'harkevich1': 'Kommander Harkevich, the Iron Wolf',
    'strakhov1': 'Kommander Oleg Strakhov',
    'butcher2': 'Kommander Orsus Zoktavir',
    'sorscha1': 'Kommander Sorscha',
    'butcher3': 'Kommander Zoktavir, the Butcher Unleashed',
    'kozlov1': 'Lord Kozlov, Viscount of Scarsgrad',
    'zerkova2': 'Obavnik Komander Zerkova & Reaver Guard',
    'oldwitch1': 'The Old Witch of Khador',
    'butcher1': 'Orsus Zoktavir, the Butcher of Khardov',
    'irusk2': 'Supreme Kommandant Irusk',
    'vlad3': 'Vladimir Tzepesci, Great Prince of Umbrey',
    'vlad2': 'Vladimir Tzepesci, the Dark Champion',
    'vlad1': 'Vladimir Tzepesci, the Dark Prince',
    'oldwitch2': 'Zevanna Agha, the Fate Keeper',
    ## Protectorate of Menoth
    'durst1': 'Anson Durst, Rock of the Faith',
    'feora1': 'Feora, Priestess of the Flame',
    'feora2': 'Feora, Protector of the Flame',
    'feora3': 'Feora, the Conquering Flame',
    'kreoss2': 'Grand Exemplar Kreoss',
    'severius1': 'Grand Scrutator Severius',
    'harbinger1': 'The Harbinger of Menoth',
    'severius2': 'Hierarch Severius',
    'amon1': 'High Allegiant Amon Ad-Raza',
    'reznik1': 'High Executioner Servath Reznik',
    'cyrenia1': 'High Exemplar Cyrenia',
    'kreoss1': 'High Exemplar Kreoss',
    'highreclaimer1': 'The High Reclaimer',
    'kreoss3': 'Intercessor Kreoss',
    'malekus1': 'Malekus, the Burning Truth',
    'reznik2': 'Servath Reznik, Wrath of Ages',
    'durant2': 'Sovereign Tristan Durant',
    'highreclaimer2': 'Testament of Menoth',
    'thyra1': 'Thyra, Flame of Sorrow',
    'vindictus1': 'Vice Scrutator Vindictus',
    ## Cryx
    'asphyxious3': 'Asphyxious the Hellbringer',
    'agathia1': 'Bane Witch Agathia',
    'aiakos2': 'Captain Aiakos',
    'deneghra3': 'Deneghra, the Soul Weaver',
    'goreshade1': 'Goreshade the Bastard',
    'goreshade2': 'Goreshade the Cursed',
    'goreshade3': 'Goreshade, Lord of Ruin',
    'asphyxious1': 'Iron Lich Asphyxious',
    'asphyxious2': 'Lich Lord Asphyxious',
    'terminus1': 'Lich Lord Terminus',
    'venethrax1': 'Lich Lord Venethrax',
    'scaverous1': 'Lord Exhumator Scaverous',
    'mortenebra1': 'Master Necrotech Mortenebra',
    'mortenebra2': 'Mortenebra, Numen of Necrogenesis',
    'skarre1': 'Pirate Queen Skarre',
    'skarre3': 'Skarre, Admiral of the Black Fleet',
    'skarre2': 'Skarre, Queen of the Broken Coast',
    'sturgis2': 'Sturgis the Corrupted',
    'deneghra1': 'Warwitch Deneghra',
    'coven1': 'The Witch Coven of Garlghast',
    'deneghra2': 'Wraith Witch Deneghra', 
    ## Retribution of Scyrah
    'rahn1': 'Adeptis Rahn',
    'vyros1': 'Dawnlord Vyros',
    'elara2': 'Elara, Death\'s Shadow',
    'garryth1': 'Garryth, the Blade of Retribution',
    'issyria1': 'Issyria, Sibyl of Dawn',
    'kaelyssa1': 'Kaelyssa, the Night\'s Whisper',
    'ossyan1': 'Lord Arcanist Ossyan',
    'goreshade4': 'Lord Ghyrrshyld, the Forgiven',
    'helynna1': 'Magister Helynna',
    'ravyn1': 'Ravyn, the Eternal Light',
    'thyron1': 'Thyron, Sword of Truth',
    'vyros2': 'Vyros, Incissar of the Dawnguard',
    ## Convergence of Cyriss
    ## Crucible Guard
    ## Mercenaries
    ## Trollbloods
    ## Circle Orboros
    ## Legion of Everblight
    ## Skorne
    ## Grymkin
    ## Minions
}