casters = {
    ## Cygnar
    'nemo3': 'Artificer General Nemo',
    'finch1': 'Storm Chaser Finch',
    'caine3': 'Caine\'s Hellslingers',
    'jakes2': 'Captain Allison Jakes',
    'caine2': 'Captain Allistar Caine',
    'darius1': 'Captain E. Dominic Darius',
    'kraye1': 'Captain Jeremiah Kraye',
    'sloan1': 'Captain Kara Sloan',
    'haley1': 'Captain Victoria Haley',
    'brisbane2': 'Colonel Markus \'Siege\' Brisbane',
    'nemo1': 'Commander Adept Nemo',
    'stryker1': 'Commander Coleman Stryker',
    'sturgis1': 'Commander Dalin Sturgis',
    'nemo2': 'General Adept Nemo',
    'caine1': 'Lieutenant Allister Caine',
    'stryker2': 'Lord Commander Stryker',
    'stryker3': 'Lord General Coleman Stryker',
    'maddox1': 'Major Beth Maddox',
    'brisbane1': 'Major Markus \'Siege\' Brisbane',
    'haley3': 'Major Prime Victoria Haley',
    'haley2': 'Major Victoria Haley',
    ## Khador
    'strakhov2': 'Assault Kommander Strakhov & Kommandos',
    'sorscha2': 'Forward Kommander Sorscha',
    'karchev1': 'Karchev the Terrible',
    'zerkova1': 'Koldun Kommander Aleksandra Zerkova',
    'irusk1': 'Kommandant Irusk',
    'sorscha3': 'Kommandant Sorscha Kratikoff',
    'malakov2': 'Kommander Andrei Malakov',
    'harkevich1': 'Kommander Harkevich, the Iron Wolf',
    'strakhov1': 'Kommander Oleg Strakhov',
    'butcher2': 'Kommander Orsus Zoktavir',
    'sorscha1': 'Kommander Sorscha',
    'butcher3': 'Kommander Zoktavir, the Butcher Unleashed',
    'kozlov1': 'Lord Kozlov, Viscount of Scarsgrad',
    'zerkova2': 'Obavnik Komander Zerkova & Reaver Guard',
    'oldwitch1': 'The Old Witch of Khador',
    'butcher1': 'Orsus Zoktavir, the Butcher of Khardov',
    'irusk2': 'Supreme Kommandant Irusk',
    'vladimir3': 'Vladimir Tzepesci, Great Prince of Umbrey',
    'vladimir2': 'Vladimir Tzepesci, the Dark Champion',
    'vladimir1': 'Vladimir Tzepesci, the Dark Prince',
    'oldwitch2': 'Zevanna Agha, the Fate Keeper',
    ## Protectorate of Menoth
    'durst1': 'Anson Durst, Rock of the Faith',
    'feora1': 'Feora, Priestess of the Flame',
    'feora2': 'Feora, Protector of the Flame',
    'feora3': 'Feora, the Conquering Flame',
    'feora4': 'Feora the Forsaken',
    'kreoss2': 'Grand Exemplar Kreoss',
    'severius1': 'Grand Scrutator Severius',
    'harbinger1': 'The Harbinger of Menoth',
    'severius2': 'Hierarch Severius',
    'amon1': 'High Allegiant Amon Ad-Raza',
    'reznik1': 'High Executioner Servath Reznik',
    'cyrenia1': 'High Exemplar Cyrenia',
    'kreoss1': 'High Exemplar Kreoss',
    'highreclaimer1': 'The High Reclaimer',
    'kreoss3': 'Intercessor Kreoss',
    'malekus1': 'Malekus, the Burning Truth',
    'reznik2': 'Servath Reznik, Wrath of Ages',
    'durant2': 'Sovereign Tristan Durant',
    'highreclaimer2': 'Testament of Menoth',
    'thyra1': 'Thyra, Flame of Sorrow',
    'vindictus1': 'Vice Scrutator Vindictus',
    ## Cryx
    'asphyxious3': 'Asphyxious the Hellbringer',
    'agathia1': 'Bane Witch Agathia',
    'aiakos2': 'Captain Aiakos',
    'deneghra3': 'Deneghra, the Soul Weaver',
    'goreshade1': 'Goreshade the Bastard',
    'goreshade2': 'Goreshade the Cursed',
    'goreshade3': 'Goreshade, Lord of Ruin',
    'asphyxious1': 'Iron Lich Asphyxious',
    'asphyxious2': 'Lich Lord Asphyxious',
    'terminus1': 'Lich Lord Terminus',
    'venethrax1': 'Lich Lord Venethrax',
    'scaverous1': 'Lord Exhumator Scaverous',
    'mortenebra1': 'Master Necrotech Mortenebra',
    'mortenebra2': 'Mortenebra, Numen of Necrogenesis',
    'skarre1': 'Pirate Queen Skarre',
    'skarre3': 'Skarre, Admiral of the Black Fleet',
    'skarre2': 'Skarre, Queen of the Broken Coast',
    'sturgis2': 'Sturgis the Corrupted',
    'deneghra1': 'Warwitch Deneghra',
    'coven1': 'The Witch Coven of Garlghast',
    'deneghra2': 'Wraith Witch Deneghra', 
    ## Retribution of Scyrah
    'rahn1': 'Adeptis Rahn',
    'vyros1': 'Dawnlord Vyros',
    'elara2': 'Elara, Death\'s Shadow',
    'garryth1': 'Garryth, the Blade of Retribution',
    'garryth2': 'Garryth, Eye of Vengeance',
    'issyria1': 'Issyria, Sibyl of Dawn',
    'kaelyssa1': 'Kaelyssa, the Night\'s Whisper',
    'ossyan1': 'Lord Arcanist Ossyan',
    'goreshade4': 'Lord Ghyrrshyld, the Forgiven',
    'helynna1': 'Magister Helynna',
    'ravyn1': 'Ravyn, the Eternal Light',
    'thyron1': 'Thyron, Sword of Truth',
    'vyros2': 'Vyros, Incissar of the Dawnguard',
    ## Convergence of Cyriss
    'aurora1': 'Aurora, the Numen of Aerogenesis',
    'locke1': 'Aurum Lucanum Athanor Locke',
    'axis1': 'Axis, the Harmonic Enforcer',
    'orion1': 'Eminent Configurator Orion',
    'lucant1': 'Father Lucant, the Divinity Architect',
    'syntherion1': 'Forge Master Syntherion',
    'directrix1': 'Iron Mother Directrix & Exponent Servitors',
    ## Crucible Guard
    'syvestro1': 'Aurum Adeptus Syvestro',
    'lukas1': 'Aurum Legate Lukas Di Morray',
    'mackay1': 'Captain Eira Mackay',
    'gearhart1': 'Marshal General Baldwin Gearhart & Mr. Clogg',
    ## Mercenaries
    'ashlynn1': 'Ashlynn D\'Elyse',
    'aurora2': 'Archnumen Aurora',
    'montador1': 'Captain Bartolo Montador',
    'damiano1': 'Captain Damiano',
    'shae1': 'Captain Phinneus Shae',
    'cyphon1': 'Cognifex Cyphon',
    'blaize1': 'Constance Blaize, Knight of the Prophet',
    'macbain1': 'Drake Macbain',
    'durgen1': 'Durgen Madhammer',
    'thexus1': 'Exulon Thexus',
    'fiona1': 'Fiona the Black',
    'ossrum1': 'General Ossrum',
    'gorten1': 'Gorten Grundback',
    'crosse2': 'Lieutenant Crosse, Resistance Fighter',
    'magnus1': 'Magnus the Traitor',
    'magnus2': 'Magnus the Warlord',
    ## Infernals
    'agathon1': 'Agathon, the Voice in the Darkness',
    'omodamos1': 'Omodamos, the Black Gate',
    'zaateroth1': 'Zaateroth, the Weaver of Shadows',
    ## Trollbloods
    'borka1': 'Borka Kegslayer',
    'borka2': 'Borka, Vengance of the Rimeshaws',
    'calandra1': 'Calandra Truthsayer, Oracle of the Glimmerwood',
    'gunnbjorn1': 'Captain Gunnbjorn',
    'gunnbjorn2': 'Brigadier General Gunnbjorn',
    'grim1': 'Grim Angus',
    'grissel1': 'Grissel Bloodsong, Fell Caller',
    'grissel2': 'Grissel Bloodsong, Marshal of the Kriels',
    'doomshaper3': 'Hoarluk Doomshaper, Dire Prophet & Scroll Bearers',
    'doomshaper2': 'Hoarluk Doomshaper, Rage of Dhunia',
    'doomshaper1': 'Hoarluk Doomshaper, Shaman of the Gnarls',
    'horgle2': 'Horgle, the Anvil',
    'grim2': 'Hunters Grim',
    'skuld1': 'Jarl Skuld, Devil of the Thornwood',
    'kolgrima1': 'Kolgrima Stonetruth, Winter Witch',
    'madrak1': 'Madrak Ironhide, Thornwood Chieftain',
    'madrak2': 'Madrak Ironhide, World Ender',
    'madrak3': 'Madrak, Great Chieftain',
    'ragnor1': 'Ragnor Skysplitter, the Runemaster',
    ## Circle Orboros
    'baldur1': 'Baldur the Stonecleaver',
    'baldur2': 'Baldur the Stonesoul',
    'thorle1': 'Bradigus Thorle the Runecarver',
    'grayle1': 'Grayle the Farstrider',
    'iona1': 'Iona the Unseen',
    'kaya2': 'Kaya the Moonhunter',
    'kaya1': 'Kaya the Wildborne',
    'kaya3': 'Kaya the Wildheart',
    'kromac1': 'Kromac the Ravenous',
    'kromac2': 'Kromac, Champion of the Wurm',
    'krueger2': 'Krueger the Stormlord',
    'krueger1': 'Krueger the Stormwrath',
    'mohsar1': 'Mohsar the Desertwalker',
    'morvahna1': 'Morvahna the Autumnblade',
    'morvahna2': 'Morvahna the Dawnshadow',
    'tanith1': 'Tanith the Feral Song',
    'una2': 'Una the Skyhunter',
    'wurmwood1': 'Wurmwood, Tree of Fate & Cassius the Oathkeeper',
    ## Legion of Everblight
    'absylonia2': 'Absylonia, Daughter of Everblight',
    'absylonia1': 'Absylonia, Terror of Everblight',
    'anamag1': 'Anamag the Doom Feaster',
    'bethayne1': 'Bethayne, Voice of Everblight',
    'bethayne2': 'Bethayne, Pride of Everblight',
    'fyanna2': 'Fyanna, Torment of Everblight',
    'kallus2': 'Kallus, Devastation of Everblight',
    'kallus1': 'Kallus, Wrath of Everblight',
    'kryssa1': 'Kryssa, Conviction of Everblight',
    'lylyth1': 'Lylyth, Herald of Everblight',
    'lylyth3': 'Lylyth, Reckoning of Everblight',
    'lylyth2': 'Lylyth, Shadow of Everblight',
    'rhyas1': 'Rhyas, Sigil of Everblight',
    'saeryn1': 'Saeryn, Omen of Everblight',
    'saeryn2': 'Saeryn & Rhyas, Talons of Everblight',
    'thagrosh1': 'Thagrosh, Prophet of Everblight',
    'thagrosh2': 'Thagrosh, the Messiah',
    'vayl2': 'Vayl, Consul of Everblight',
    'vayl1': 'Vayl, Disciple of Everblight',
    ## Skorne
    'makeda1': 'Archdomina Makeda',
    'xekaar1': 'Beast Master Xekaar',
    'morghoul3': 'Dominar Morghoul & Escorts',
    'rasheth1': 'Dominar Rasheth',
    'hexeris2': 'Lord Arbiter Hexeris',
    'morghoul2': 'Lord Assassin Morghoul',
    'hexeris1': 'Lord Tyrant Hexeris',
    'zaadesh2': 'Lord Tyrant Zaadesh',
    'makeda3': 'Makeda & the Exhalted Court',
    'naaresh1': 'Master Ascetic Naaresh',
    'morghoul1': 'Master Tormentor Morghoul',
    'jalaam1': 'Primus Jalaam',
    'zaal1': 'Supreme Aptimus Zaal',
    'makeda2': 'Supreme Archdomina Makeda',
    'xerxis1': 'Tyrant Xerxis',
    'mordikaar1': 'Void Seer Mordikaar',
    'xerxis2': 'Xerxis, Fury of Halaak',
    'zaal2': 'Zaal, the Ancestral Advocate',
    ## Grymkin
    'child1': 'The Child',
    'dreamer1': 'The Dreamer',
    'heretic1': 'The Heretic',
    'kingofnothing1': 'The King of Nothing',
    'wanderer1': 'The Wanderer',
    'oldwitch3': 'Zevanna Agha, the Fate Keeper',
    ## Minions
    'azazello1': 'Lord Azazello, the Castellan',
    'barnabas2': 'Barnabas, Lord of Blood',
    'barnabas1': 'Bloody Barnabas',
    'calaban1': 'Calaban, the Grave Walker',
    'arkadius1': 'Dr. Arkadius',
    'helga1': 'Helga the Conquerer',
    'helga2': 'Helga on Wheels',
    'jagajaga1': 'Jaga-Jaga, the Death Charmer',
    'carver1': 'Lord Carver, BMMD, Esq. III',
    'maelok1': 'Maelok the Dreadbound',
    'midas1': 'Midas',
    'rask1': 'Rask',
    'sturm1': 'Sturm & Drang'
}